package com.putable.tilenet.Util.XMLTags;

import org.xml.sax.Attributes;

public class LogoutTag extends XMLTag {
	private String message;

	/**
	 * Constructor for LogoutTag creation in client.
	 * 
	 * @param message
	 */
	public LogoutTag(String message) {
		super(TagType.LOGOUT);
		this.message = message;

	}

	/**
	 * Constructor for LogoutTag creation in parser.
	 * 
	 * @param atts
	 *            are generated by the sax parser.
	 */
	public LogoutTag(Attributes atts) {
		super(TagType.LOGOUT);
		this.message = atts.getValue("message");
	}

	public String getMessage() {
		return message;
	}

	@Override
	public String toString() {
		return "<logout message=\"" + message + "\"/>\n</client>";

	}
}
